language: cpp
compiler:
- gcc
before_install:
- sudo apt-get update -qq
install:
- wget http://www.biicode.com/downloads/latest/ubuntu64
- mv ubuntu64 bii-ubuntu64.deb
- sudo dpkg -i bii-ubuntu64.deb && sudo apt-get -f install
- rm bii-ubuntu64.deb
- wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz
- tar -xzf cmake-3.0.2-Linux-64.tar.gz
- sudo cp -fR cmake-3.0.2-Linux-64/* /usr
- rm -rf cmake-3.0.2-Linux-64
- rm cmake-3.0.2-Linux-64.tar.gz
script:
- cmake --version
- bii init biicode_project
- mkdir -p ./biicode_project/blocks/Maria/trial
- mv !(biicode_project) ./biicode_project/blocks/Maria/trial
- cd biicode_project
- bii cpp:build
- ./bin/Maria_trial_main
after_success:
- echo ""Getting tag $TRAVIS_TAG
- bii user Maria -p $BII_MARIA_PASSWORD
- bii publish --tag STABLE --versiontag=$TRAVIS_TAG

env:
  global:
    secure: A8R679/naORNh7D0Myj0zHbPgdEvxUYFlIeAvKAwA4yxMXjE9NiNe18xTYqmGb/p4wG/diKMCn+WMJ34iHdNR5VQEQnZonImBsflRwzASBxGDofM+RFDCmVFfBYBQcIWm5nvvRgy05DCQg+g57nRklqXTE38W67i2/6pwwmBvrU=
