version: 1.0.{build}

branches:
  only: 
    - CI/appveyor

skip_commits:
  message: /Updated biicode parents/

install:
  - ps: wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-win32-x86.zip -OutFile cmake.zip
  - cmd: echo "Unzipping cmake..."
  - cmd: 7z x cmake.zip -o"C:\Program Files (x86)\" -y > nul
  - cmd: set PATH=%PATH:CMake 2.8\bin=%;C:\Program Files (x86)\cmake-3.0.2-win32-x86\bin
  - cmd: cmake --version
  - cmd: echo "Downloading biicode..."
  - ps: wget http://www.biicode.com/downloads/latest/win -OutFile bii-win.exe
  - cmd: bii-win.exe /VERYSILENT
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\BiiCode\bii
  - cmd: bii -v
  - cmd: del bii-win.exe
  - cmd: del cmake.zip

before_build:
  - cmd: bii init %project_name%
  - cmd: cd %project_name%
  - cmd: bii new %block_user%/%block_name%
    # move the files
  - cmd: for %%i in (../*) do if %%i NEQ "%project_name%" move "..\%%i" blocks\%block_user%\%block_name%\
    # move the directories -> there are none
  # cmd: for /d %%i in (../*) do if %%i NEQ "%project_name%" move "..\%%i" blocks\%block_user%\%block_name%\
  - cmd: bii cpp:configure -G "Visual Studio 12"

build_script:
  - cmd: bii cpp:build

test_script:
  - cmd: cd bin
  - cmd: Maria_trial_main.exe

deploy:
  - provider: GitHub
    auth_token:%github_token%
    draft: false
    prerelease: false
    on:
      branch: CI/appveyor            # release from CI/appveyor branch only
      appveyor_repo_tag: true        # deploy on tag push only

# to run your custom scripts instead of provider deployments
deploy_script:
  - cmd: bii user %block_user% -p %secured_passwd%
  - if defined APPVEYOR_REPO_TAG_NAME set VERSION=%APPVEYOR_REPO_TAG_NAME%  
  - echo "Building tagged release %VERSION%"
  - if not defined APPVEYOR_REPO_TAG_NAME set VERSION=%no_version%
  - cmd: bii publish --tag=%tag% --versiontag=%VERSION% #|| dir # Ignore output

environment:
  project_name:
    "myproject"
  block_user:
    "Maria"
  block_name:
    "trial"
  secured_passwd:
    secure: ZMvgETfLAUo7kISnvrinBA==
  github_token:
    secure: s7IoFbHLebmL2SBjEH7VOKfO8VYsZmvklqb3NcN11+G+jXui5Dx4T5eEO97o0lEj
  tag:
    "STABLE"
  no_version:
    ""
